# config/train_config.yaml

block_size: 128
vocab_size: 50304

n_layer: 4
n_head: 4
n_embd: 256
dropout: 0.3

batch_size: 64

learning_rate: 3e-4
min_lr: 1e-5
weight_decay: 1e-2

warmup_epochs: 5
epochs: 5

